#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the ignisda.me applications

# change to the project folder
cd "$HOME/ignisda.me"

# directory path of django development server
backend_folder="backend"
# directory path of nuxt development server
frontend_folder="frontend"

# Start all the servers
{ cd "$backend_folder" && poetry run python3 manage.py runserver 0.0.0.0:8000 & \
  cd "$frontend_folder" && yarn dev; }
